# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FloatButtonToScroll' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FloatButtonToScroll

end

target 'FloatButtonToScrollExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FloatButtonToScrollExample

end
